// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChannelPermissions string
	ChannelUsers       string
	Channels           string
	HubPermissions     string
	HubUsers           string
	Hubs               string
	Messages           string
	Users              string
}{
	ChannelPermissions: "channel_permissions",
	ChannelUsers:       "channel_users",
	Channels:           "channels",
	HubPermissions:     "hub_permissions",
	HubUsers:           "hub_users",
	Hubs:               "hubs",
	Messages:           "messages",
	Users:              "users",
}
